name: Deploy

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
  
    steps:
    - uses: appleboy/ssh-action@master
      with:    
        host: ec2-54-252-206-212.ap-southeast-2.compute.amazonaws.com
        username: ubuntu
        key_path: .github/workflows/key.pem
        script: .github/workflows/Deploy.sh