name: Deploy

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
  
    steps:
    - uses: actions/checkout@v3
    - name: Install OpenSSH
      run: |
        sudo apt-get install openssh-client

    - name: Open SSH
      run: |
        cd .github/workflows
        chmod 400 key.pem
        ssh -tt -i "key.pem" ubuntu@ec2-54-252-206-212.ap-southeast-2.compute.amazonaws.com